update workflow

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -1,22 +1,41 @@
 name: autofix.ci
+
 on:
   push:
+
 permissions:
   contents: write
   actions: write
+
 jobs:
   prettier:
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v4
+
       - uses: actions/setup-node@v4
-      - run: |
-          yarn
-          yarn prettier . --check
-          if [ $? -eq 0 ]; then
+
+      - run: yarn
+
+      - name: Auto-fix formatting
+        run: |
+          yarn prettier . --check || true
+          status=$?
+
+          if [ $status -eq 1 ]; then
+            echo "Formatting issues found. Running prettier --write"
+            yarn prettier . --write
+
+          elif [ $status -eq 2 ]; then
+            echo "Prettier error occurred"
+            exit 1
+
+          else
+            echo "No formatting issues. Skipping autofix."
             exit 0
           fi
-          yarn prettier . --write
+
       - uses: autofix-ci/action@v1
         with:
           commit-message: "Apply Prettier format"
